'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EasyLLM_V2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CGMono_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CGMono_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE IF NOT EXISTS Users (
        '''	Username TEXT PRIMARY KEY,
        '''	IsAdmin INTEGER NOT NULL DEFAULT 0
        ''');
        '''
        '''CREATE TABLE IF NOT EXISTS Materials (
        '''	ReferenceNumber INTEGER PRIMARY KEY,
        '''	PartNumber TEXT NOT NULL,
        '''	PartDescription TEXT NOT NULL,
        '''	LotNumber TEXT NOT NULL,
        '''	ExpirationDate TEXT,
        '''	DisplayAutoRef INTEGER NOT NULL DEFAULT 1
        ''');
        '''
        '''CREATE TABLE IF NOT EXISTS UserStock (
        '''	ReferenceNumber INTEGER,
        '''	CheckedOutUser TEXT,
        '''	CheckedOutTimestamp TIMESTAMP,
        '''	FOREIGN KEY (ReferenceNumber) REFERENCES [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DbInit() As String
            Get
                Return ResourceManager.GetString("DbInit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property LLM_History() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("LLM_History", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property SOAR_5() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SOAR_5", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
